export const SET_GAP = "SET_GAP";
export const SET_CLOSING_TIME = "SET_CLOSING_TIME";
export const FETCH_LAST_BREAK_TIME = "FETCH_LAST_BREAK_TIME";
export const SET_LAST_BREAK_TIME = "SET_LAST_BREAK_TIME";
export const SET_BREAK_NOTIFICATION_HEADER = "SET_BREAK_NOTIFICATION_HEADER";
export const SET_BREAK_NOTIFICATION_TEXT = "SET_BREAK_NOTIFICATION_TEXT";
export const SET_END_NOTIFICATION_HEADER = "SET_END_NOTIFICATION_HEADER";
export const SET_END_NOTIFICATION_TEXT = "SET_END_NOTIFICATION_TEXT";
